version: '3'

services:
    app:
        build:
            context: docker/app
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/html
            - ./docker/app/config.ini:/usr/local/etc/php/conf.d/config.ini
        networks:
            - setup-network

    nginx:
        image: nginx:1.23
        restart: unless-stopped
        tty: true
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - setup-network

    mysql:
        image: mysql:8.1
        command: --default-authentication-plugin=caching_sha2_password
        restart: always
        tty: true
        volumes:
            - setup-data:/var/lib/mysql/
            - ./docker/mysql/mysql.cnf:/etc/mysql/mysql.cnf
        networks:
            - setup-network
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    cron:
        build:
            context: docker/cron
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - setup-network

    supervisor:
        build:
            context: docker/supervisor
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - setup-network


networks:
    setup-network:
        driver: bridge

volumes:
    setup-data:
        driver: local
